

name: CI - Pipeline de Dados Pokémon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      
      - name: Criar arquivo .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> pokedb.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> pokedb.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> pokedb.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> pokedb.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> pokedb.env
          echo "Arquivo .env criado com sucesso."

      - name: Rodar script de ingestão (Prefect)
        run: python3 ingestions.py

     
      - name: Configurar perfil do dbt
        run: |
          mkdir -p ~/.dbt
          echo "poke_dbt:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: postgres" >> ~/.dbt/profiles.yml
          echo "      host: ${{ secrets.DB_HOST }}" >> ~/.dbt/profiles.yml
          echo "      port: ${{ secrets.DB_PORT |_default(5432) }}" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.DB_USER }}" >> ~/.dbt/profiles.yml
          echo "      pass: ${{ secrets.DB_PASSWORD }}" >> ~/.dbt/profiles.yml
          echo "      dbname: ${{ secrets.DB_NAME }}" >> ~/.dbt/profiles.yml
          echo "      schema: public" >> ~/.dbt/profiles.yml

      - name: Rodar dbt build
        run: dbt build --project-dir ./poke_dbt
